### ISSUE TITLE
Add README image

### ISSUE THREAD

**Issue by willviles** [PotentialWeb/CoronaTab#1]
![screenshot](https://user-images.githubusercontent.com/2046935/76784350-63397580-67ab-11ea-8854-4bb20dbca3e9.jpg)

**Comment by nodeful** [comment]
![coronatab](https://user-images.githubusercontent.com/8472525/77709538-52ff7280-6fc3-11ea-84ca-a23b9b348b95.JPG)

maybe time to update 👅
