### ISSUE TITLE
Regional pane issues

### ISSUE THREAD

**Issue by jay** [PotentialWeb/CoronaTab#23]
In the animated GIF below you can see that when the region is changed the page will change position. Taken at 1920 wide (full screen).

![d](https://user-images.githubusercontent.com/965580/78220070-d111bc80-748e-11ea-9d09-5e4de56c5079.gif)

In the animated GIF below you can see that if the width is smaller (like 900) then there is a different problem, the Daily pane will fail to expand.

![e](https://user-images.githubusercontent.com/965580/78220083-d7079d80-748e-11ea-8e34-f65381e5c75b.gif)

Chrome for desktop 80.0.3987.149
Windows 7 Enterprise

**Comment by willviles** [comment]
Thanks @jay, much appreciated! Fixed in https://github.com/PotentialWeb/CoronaTab/commit/ee09b5177fd83bbc15db3a579127cfd478641cde.
