### ISSUE TITLE
Data not updated after 17 april

### ISSUE THREAD

**Issue by ramveer93** [PotentialWeb/CoronaTab#27]
I am not able to see the data after 17th April, Is it not updated. What is schedule to update the data.

**Comment by nodeful** [comment]
The process is semi manual and we've been updating data while trying to get people using the product, but unfortunately it hasn't gained much traction so we think we won't continue maintaining it further.

**Comment by ramveer93** [comment]
I am using your APIs in my dashboard to show world dashboard here : https://corona-india19.el.r.appspot.com/world
I know that is very small but in case If that convinces you to update the data.

**Comment by nodeful** [comment]
Have you seen complexity of our API? It's fully relational with nested places structure. It just takes about an hour every day to update it, which we can't afford for a dead project...
