### ISSUE TITLE
CORS policy error

### ISSUE THREAD

**Issue by prav2508** [PotentialWeb/CoronaTab#28]
I get the below error when i try to access the API,
Error :
Access to XMLHttpRequest at 'https://api.coronatab.app/places' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Please help!

**Comment by willviles** [comment]
Please refer to https://github.com/PotentialWeb/CoronaTab/wiki/RESTful-API-documentation.

"We have Origin CORS policies set to only allow coronatab.app domain, so you won't be able to access our API directly from any site, therefore we encourage you to fetch the data and store it on your server, or another option is to setup a Reverse proxy."
