### ISSUE TITLE
Results returning for future dates

### ISSUE THREAD

**Issue by paparush** [PotentialWeb/CoronaTab#29]
Executing this query on 4/23/2020:
https://api.coronatab.app/places/united-states-of-america-north-carolina-buncombe-county/data?compact=true

Returns dates through 5/5/2020

**Comment by nodeful** [comment]
If you look closer it's the projected dates in the the meta object

**Comment by paparush** [comment]
Thank you for the reply.

I guess I was confused because the wiki mentions neither meta object or
projected dates.

**Comment by nodeful** [comment]
Yeah I haven't documented that. To be honest this project hasn't gained much traction so we can't afford to maintain it much longer. But feel free to fork the code and use it as you wish, all the scraping logic is there and uses https://github.com/covidatlas/coronadatascraper internally.
