### ISSUE TITLE
Improve data integrity & sources

### ISSUE THREAD

**Issue by willviles** [PotentialWeb/CoronaTab#9]
Consider: 

- Working with [lazd/coronadatascraper](https://github.com/lazd/coronadatascraper) to scrape data and write scrapers there for any sources we'd like.
- Implementing crowdsourcing solutions

**Comment by nodeful** [comment]
With the acceleration of cases and gradual improvements to the API's and Sources we are using the crowdsourcing idea kinda stops making sense. Better focus on cool features like widget + locales + projections
